# Generated by Django 5.0.1 on 2024-01-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_comment_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
